In [2]:
import pandas as pd

In [4]:
ABPhysician = pd.read_csv('./csv/AB Physician.csv')
#BCPhysician
MAPhysician = pd.read_csv('./csv/MA Physician.csv')
SKPhysician = pd.read_csv('./csv/SK Physician.csv')
NFPhysician = pd.read_csv('./csv/NF Physician.csv')
#NBPhysician = pd.read_csv('./csv/NB Pharmacy.csv')
PEIPhysician = pd.read_csv('./csv/PEI Physician.csv')

ABPharmacy = pd.read_csv('./csv/AB Pharmacy.csv')
BCPharmacy = pd.read_csv('./csv/BC Pharmacy.csv')
MAPharmacy = pd.read_csv('./csv/MA Pharmacy.csv')
SKPharmacy = pd.read_csv('./csv/SK Pharmacy.csv')
NBPharmacy = pd.read_csv('./csv/NB Pharmacy.csv')
NFPharmacy = pd.read_csv('./csv/NF Pharmacy.csv')
PEIPharmacy = pd.read_csv('./csv/PEI Pharmacy.csv')
NSPharmacy = pd.read_csv('./csv/NS Pharmacy.csv')

FileNotFoundError: File b'./csv/SK Pharmacy.csv' does not exist

In [111]:
ABPhysician.rename(columns={'Practice Discipline': 'Specialty'}, inplace=True)
ABPhysician.head()

,Specialty,Postal Code,Lat/Long,First Name,Last Name,City,Latitude,Longtitude,Street
0,Family Medicine,T4N 3P7,"52.271794,-113.804234",Wayne F.,Church,Red Deer,52.271794,-113.804234,6-5030 47 AVE
1,General Practice,T0A 0M0,"54.6417493,-112.8073056",Johanna Catharina,Cilliers,Boyle,54.6417493,-112.807306,PO BOX 329
2,Anesthesiology,T8N 6W6,"53.653477,-113.588269",Patrick G.,Cisar,St. Albert,53.653477,-113.588269,50 KINGSBURY CRES
3,Family Medicine,T1A 6N9,"50.049596,-110.6880581",Sergiu,Ciubotaru,Medicine Hat,50.049596,-110.688058,49 8 ST NW
4,Family Medicine,T4N 3Y4,"52.255393,-113.8147902",Cornelis Johannes,Claasen,Red Deer,52.255393,-113.814790,3410 50 AVE

In [56]:
MAPhysician.rename(columns={'Speciality': 'Specialty'}, inplace=True)
MAPhysician.head()

,Street,City,Postal Code,Specialty,Lat/Long,Latitude,Longtitude,DAUID,First Name,Last Name
0,"Thompson Clinic, 50 Selkirk Avenue",Thompson,R8N 0M7,NaN,"55.741576,-97.854843",55.741576,-97.854843,46220102.0,Chukwuma Solomon,Abara
1,"Health Sciences Centre, Section of Neonatology...",Winnipeg,R3A 1R9,NaN,"49.903595,-97.157159",49.903595,-97.157159,46110136.0,Nizar Rizk,Abazid
2,"Seven Oaks General Hospital, 2300 McPhillips S...",Winnipeg,R2V 3M3,NaN,"49.950584,-97.144524",49.950584,-97.144524,46110036.0,Burton Bjorn,Abbott
3,"Dr. C.W. Wiebe Medical Centre, 385 Main Street",Winkler,R6W 1J2,NaN,"49.18186,-97.939475",49.181860,-97.939475,46030095.0,Ganesan Palani,Abbu
4,"Manitoba Clinic, 790 Sherbrook Street",Winnipeg,R3A 1M3,"Internal Medicine, Gastroenterology","49.901693,-97.15804",49.901693,-97.158040,46110136.0,Ibrahim Mohamed Ali,Abdelgadir

In [57]:
SKPhysician.rename(columns={'LastName': 'Last Name', 'FirstName': 'First Name', 'Speciality': 'Specialty'}, inplace=True)
SKPhysician.head()

,Last Name,Postal Code,City,First Name,Specialty,Lat/Long,Latitude,Longtitude,DAUID
0,Torlakovic,S7N 0W8,Saskatoon,Emina,Anatomic and Clinical Pathology,"52.130532,-106.641326",52.130532,-106.641326,47110106.0
1,Balachandra,T6H 5R8,Edmonton,Thambirajah,Anatomical Pathology,"53.505024,-113.531279",53.505024,-113.531279,NaN
2,Diudea,S7N 0W8,Saskatoon,Dana,Anatomical Pathology,"52.130532,-106.641326",52.130532,-106.641326,47110106.0
3,Shokeir,S9A 1Z1,North Battleford,Marc,Anatomical Pathology,"52.773433,-108.288718",52.773433,-108.288718,47160226.0
4,Shukoor,S9H 2J9,Swift Current,Sajid,Anatomical Pathology,"50.288224,-107.79479",50.288224,-107.794790,47080150.0

In [58]:
NFPhysician.rename(columns={'Address': 'Street'}, inplace=True)
NFPhysician.drop(columns={'Member Type', 'Unnamed: 0'}, inplace=True)
NFPhysician.loc[1,'Street']
NFPhysician.head()

KeyError: "['Member Type' 'Unnamed: 0'] not found in axis"

In [59]:
NBPhysician.head()

,Last Name,First Name,Street,City,Postal Code,Specialty,Lat/Long,Latitude,Longtitude,DAUID
0,Abbass,S. Ali Asghar,65 Kingswood Drive,King City,L7B 1K8,Ana,"43.970375,-79.550108",43.970375,-79.550108,NaN
1,Abbass,Syed Ali Akbar,437 Roncesvalles Avenue,Toronto,M6R 3B9,Ana,"43.652241,-79.45108",43.652241,-79.451080,NaN
2,Abdel Samad,Nizar,100 Arden Street,Moncton,E1C 4B7,Hem MOn,"46.105926,-64.807077",46.105926,-64.807077,13070078.0
3,Abdelsalam,Mahmoud,100 Arden Street,Moncton,E1C 4B7,MOn,"46.105926,-64.807077",46.105926,-64.807077,13070078.0
4,Abed Sangani,Masoud,100 Arden Street,Moncton,E1C 4B7,Neu,"46.105926,-64.807077",46.105926,-64.807077,13070078.0

In [60]:
PEIPhysician.rename(columns={'Speciality': 'Specialty'}, inplace=True)
PEIPhysician.head()

,Postal Code,Street,Specialty,Lat/Long,Latitude,Longtitude,DAUID,First Name,Last Name
0,C1A 8T5,"Queen Elizabeth Hospital, Box 6000",Internal Medicine,"46.255707,-63.10236",46.255707,-63.102360,11020255.0,Lenley,Adams
1,C0B 1V0,"O'Leary Health Centre, 15 MacKinnon Drive",Family Medicine,"46.6845715,-64.2644808",46.684572,-64.264481,11030094.0,Hala,Alsalih
2,C1A 6Y1,"Sherwood Medical Centre, 15 Brackley Pt. Rd",Family Medicine,"46.263689,-63.120169",46.263689,-63.120169,11020143.0,Megan,Armstrong
3,C1N 3N9,"Summerside Medical Centre, 475 Granville St",Family Medicine,"46.416997,-63.779126",46.416997,-63.779126,11030126.0,Nadine,Arsenault-Samson
4,C1A 8T5,"Ambulatory Care, QEH Box 6600",General Surgery,"46.255707,-63.10236",46.255707,-63.102360,11020255.0,David,Ashby

In [99]:
masterPhysicianDf = pd.concat([PEIPhysician,NBPhysician, NFPhysician, SKPhysician, MAPhysician], ignore_index=True, sort=True)
pd.DataFrame(masterDf['Specialty'].unique()).to_csv('./csv/Specialty List.csv', index=False, header=False)

In [103]:
ABPharmacy.head()

,Name,Street,City,Postal Code,Lat/Long,Latitude,Longtitude,DAUID
0,Airdrie Medical Remedy's Rx Pharmacy,10-620 1 Ave NW,Airdrie,T4B 2R3,"51.2927360534668,-114.019645690918",51.292736,-114.019646,48062117.0
1,Apple Pharmacy,229 1 St SW,Airdrie,T4B 3L8,"51.2899856567383,-114.014785766602",51.289986,-114.014786,48062118.0
2,Calgary Co-Op Pharmacy #19,100-2700 Main St SE,Airdrie,T4B 2Y1,"51.2685699462891,-114.008239746094",51.268570,-114.008240,48061760.0
3,Creekside Pharmacy,1113-403 Mackenzie Way SW,Airdrie,T4B 3V7,"51.2880897521973,-114.022399902344",51.288090,-114.022400,48062425.0
4,Drugstore Pharmacy #1540,300 Veteran's Blvd NE,Airdrie,T4B 3P2,"51.3001594543457,-114.006591796875",51.300159,-114.006592,48062114.0

In [104]:
NBPharmacy.head()

,Name,Street,City,Postal Code,Lat/Long,Latitude,Longtitude,DAUID
0,Albert County Pharmacy,5883 King Street,Riverside-Albert,E4H 4B5,"-0.3232974,-78.5367005",-0.323297,-78.536700,NaN
1,Bay Pharmacy,5447 Route 117,Baie Ste Anne,E9A 1E5,"-0.1183861,-78.4700232",-0.118386,-78.470023,NaN
2,Bayshore Pharmacy,600 Main Street Suite C 150,Saint John,E2K 1J5,"45.274648,-66.07315",45.274648,-66.073150,13010146.0
3,Bioscript Pharmacy,585 Mapleton Road Suite 202,Moncton,E1G 2K5,"46.1214504,-64.8282629",46.121450,-64.828263,13070100.0
4,Blackville Pharmasave # 554,175 Main Street,Blackville,E9B 1S3,"-0.2295692,-78.5032168",-0.229569,-78.503217,NaN